missions_list = {
	{
		mission = 1,
		type = "time",
		modifier = 45,
	},
	{
		mission = 2,
		type = "logic",
		modifier = "board",
		start = {
			{index = 1, color = "gray", powerup = ""},
			{index = 2, color = "gray", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "gray", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		}
	},
	{
		mission = 3,
		type = "picture",
		name = "Star",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 4,
		type = "picture",
		name = "Sunflower",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 5,
		type = "logic",
		modifier = "black",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 6,
		type = "picture",
		name = "Triceratops",
		start = {
			{index = 1, color = "gray", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "gray", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		},
	},
	{
		mission = 7,
		type = "picture",
		name = "Big Truck",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "gray", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		},
		goal = {
			{index = 1, color = "gray", powerup = ""},
			{index = 2, color = "gray", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "gray", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
	},
	{
		mission = 8,
		type = "picture",
		name = "Cat",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "gray", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 9,
		type = "logic",
		modifier = "gray",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "none", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		}
	},
	{
		mission = 10,
		type = "picture",
		name = "Chessboard",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 11,
		type = "logic",
		modifier = "white",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "none", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		}
	},
	{
		mission = 12,
		type = "logic",
		modifier = "2x",
		start = {
			{index = 1, color = "none", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "none", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "gray", powerup = "double"},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "gray", powerup = "double"},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "gray", powerup = "double"},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "gray", powerup = "double"},
			{index = 19, color = "white", powerup = ""},
		}
	},
	{
		mission = 13,
		type = "picture",
		name = "Santa",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "gray", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "gray", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
		goal = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
	},
	{
		mission = 14,
		type = "speedrun",
		modifier = "board",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "gray", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		}
	},
	{
		mission = 15,
		type = "picture",
		name = "Old Bike",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 16,
		type = "time",
		modifier = 42,
	},
	{
		mission = 17,
		type = "picture",
		name = "Sunrise",
		start = {
			{index = 1, color = "gray", powerup = ""},
			{index = 2, color = "gray", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "gray", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "gray", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		},
	},
	{
		mission = 18,
		type = "time",
		modifier = 39,
	},
	{
		mission = 19,
		type = "picture",
		name = "Pac-Man",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		},
	},
	{
		mission = 20,
		type = "picture",
		name = "Starfish",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "gray", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "gray", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "gray", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
	},
	{
		mission = 21,
		type = "logic",
		modifier = "wild",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = "wild"},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "white", powerup = "wild"},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "white", powerup = "wild"},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = "wild"},
			{index = 15, color = "gray", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		}
	},
	{
		mission = 22,
		type = "picture",
		name = "Candy",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 23,
		type = "picture",
		name = "Illusion",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
		goal = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
	},
	{
		mission = 24,
		type = "logic",
		modifier = "2x",
		start = {
			{index = 1, color = "none", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "gray", powerup = "double"},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "gray", powerup = "double"},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "white", powerup = "double"},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = "double"},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "gray", powerup = "double"},
		}
	},
	{
		mission = 25,
		type = "logic",
		modifier = "bomb",
		start = {
			{index = 1, color = "none", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "none", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = "bomb"},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		}
	},
	{
		mission = 26,
		type = "speedrun",
		modifier = "black",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		}
	},
	{
		mission = 27,
		type = "picture",
		name = "Dog",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 28,
		type = "speedrun",
		modifier = "gray",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "none", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		}
	},
	{
		mission = 29,
		type = "time",
		modifier = 36,
	},
	{
		mission = 30,
		type = "time",
		modifier = 33,
	},
	{
		mission = 31,
		type = "time",
		modifier = 30,
	},
	{
		mission = 32,
		type = "speedrun",
		modifier = "white",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "none", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "gray", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		}
	},
	{
		mission = 33,
		type = "time",
		modifier = 27,
	},
	{
		mission = 34,
		type = "logic",
		modifier = "board",
		start = {
			{index = 1, color = "gray", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "gray", powerup = "bomb"},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "white", powerup = "wild"},
			{index = 6, color = "white", powerup = "wild"},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "white", powerup = "wild"},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "gray", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "white", powerup = "wild"},
			{index = 19, color = "white", powerup = "wild"},
		}
	},
	{
		mission = 35,
		type = "speedrun",
		modifier = "2x",
		start = {
			{index = 1, color = "none", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "none", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "gray", powerup = "double"},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "gray", powerup = "double"},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "gray", powerup = "double"},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "gray", powerup = "double"},
		}
	},
	{
		mission = 36,
		type = "time",
		modifier = 24,
	},
	{
		mission = 37,
		type = "speedrun",
		modifier = "wild",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = "wild"},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "white", powerup = "wild"},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "white", powerup = "wild"},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = "wild"},
			{index = 15, color = "gray", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		}
	},
	{
		mission = 38,
		type = "time",
		modifier = 21,
	},
	{
		mission = 39,
		type = "speedrun",
		modifier = "2x",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "gray", powerup = "double"},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "none", powerup = ""},
			{index = 6, color = "white", powerup = "double"},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = "double"},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "gray", powerup = "double"},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "white", powerup = "double"},
			{index = 19, color = "white", powerup = ""},
		}
	},
	{
		mission = 40,
		type = "picture",
		name = "Pyramids",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
	},
	{
		mission = 41,
		type = "picture",
		name = "Snake",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "black", powerup = ""},
			{index = 5, color = "black", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 42,
		type = "time",
		modifier = 18,
	},
	{
		mission = 43,
		type = "picture",
		name = "Jet",
		start = {
			{index = 1, color = "black", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "black", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 44,
		type = "speedrun",
		modifier = "bomb",
		start = {
			{index = 1, color = "none", powerup = ""},
			{index = 2, color = "none", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "none", powerup = ""},
			{index = 5, color = "none", powerup = ""},
			{index = 6, color = "gray", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "white", powerup = "bomb"},
			{index = 17, color = "black", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		}
	},
	{
		mission = 45,
		type = "picture",
		name = "Sierpinski",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "black", powerup = ""},
		},
		goal = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "black", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "black", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "black", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 46,
		type = "logic",
		modifier = "2x",
		start = {
			{index = 1, color = "white", powerup = "double"},
			{index = 2, color = "white", powerup = "wild"},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = "double"},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "black", powerup = "double"},
			{index = 9, color = "black", powerup = "double"},
			{index = 10, color = "gray", powerup = "double"},
			{index = 11, color = "black", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = "double"},
			{index = 14, color = "gray", powerup = "double"},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "white", powerup = "double"},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		}
	},
	{
		mission = 47,
		type = "speedrun",
		modifier = "board",
		start = {
			{index = 1, color = "white", powerup = "wild"},
			{index = 2, color = "black", powerup = ""},
			{index = 3, color = "gray", powerup = "bomb"},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "gray", powerup = ""},
			{index = 6, color = "black", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "black", powerup = ""},
			{index = 10, color = "white", powerup = "wild"},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = "wild"},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "black", powerup = ""},
			{index = 15, color = "gray", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "white", powerup = "wild"},
			{index = 19, color = "white", powerup = "wild"},
		}
	},
	{
		mission = 48,
		type = "speedrun",
		modifier = "2x",
		start = {
			{index = 1, color = "white", powerup = "double"},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "white", powerup = "wild"},
			{index = 5, color = "white", powerup = "double"},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "gray", powerup = "double"},
			{index = 9, color = "black", powerup = "double"},
			{index = 10, color = "black", powerup = "double"},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "black", powerup = "double"},
			{index = 14, color = "gray", powerup = "double"},
			{index = 15, color = "black", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "white", powerup = "double"},
			{index = 18, color = "black", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		}
	},
	{
		mission = 49,
		type = "picture",
		name = "Tree",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "gray", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "black", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "gray", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "gray", powerup = ""},
			{index = 16, color = "white", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "gray", powerup = ""},
		},
		goal = {
			{index = 1, color = "gray", powerup = ""},
			{index = 2, color = "gray", powerup = ""},
			{index = 3, color = "gray", powerup = ""},
			{index = 4, color = "gray", powerup = ""},
			{index = 5, color = "gray", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "gray", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "gray", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "white", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "black", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
	{
		mission = 50,
		type = "picture",
		name = "Pumpkin",
		start = {
			{index = 1, color = "white", powerup = ""},
			{index = 2, color = "gray", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "white", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "gray", powerup = ""},
			{index = 9, color = "white", powerup = ""},
			{index = 10, color = "gray", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "gray", powerup = ""},
			{index = 18, color = "white", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
		goal = {
			{index = 1, color = "gray", powerup = ""},
			{index = 2, color = "white", powerup = ""},
			{index = 3, color = "white", powerup = ""},
			{index = 4, color = "white", powerup = ""},
			{index = 5, color = "gray", powerup = ""},
			{index = 6, color = "white", powerup = ""},
			{index = 7, color = "white", powerup = ""},
			{index = 8, color = "white", powerup = ""},
			{index = 9, color = "gray", powerup = ""},
			{index = 10, color = "white", powerup = ""},
			{index = 11, color = "white", powerup = ""},
			{index = 12, color = "white", powerup = ""},
			{index = 13, color = "white", powerup = ""},
			{index = 14, color = "gray", powerup = ""},
			{index = 15, color = "white", powerup = ""},
			{index = 16, color = "gray", powerup = ""},
			{index = 17, color = "white", powerup = ""},
			{index = 18, color = "gray", powerup = ""},
			{index = 19, color = "white", powerup = ""},
		},
	},
}